# CME 211 Lecture 10 - Numpy

## Motivation

### Python is kind of slow

One of the main disadvantages of a higher level language is that, while
comparatively easy to program, it is typically slow compared to C/C++, Fortran,
or other lower level languages

![fig](fig/python-v-compiled.png)

### Object overhead

![fig](fig/object-overhead.png)

## Options for better performance

* Python is great for quick projects, prototyping new ideas, etc.

* What if you need better performance?

* One option is to completely rewrite your program in something like C/C++

### Python C API

* Python has a C API which allows the use of compiled modules

![fig](fig/python-c-interface.png)

* The actual implementation of `string.find()` can be viewed at:

http://svn.python.org/view/python/trunk/Objects/stringlib/fastsearch.h

### Python compiled modules

* Python code in a `.py` file is actually executed in a hybrid approach by a mix
  of the interpreter and compiled modules that come with Python

![fig](fig/python-compiled-modules.png)

### Extension modules

* The same Python C API used by the developers of Python itself also allows
  other programmers to develop and build their own compiled extension modules

* These modules extend the functionality of Python with high performance
  implementations of common operations

* Other languages, such as C++ and Fortran, are also supported by using the C
  API

### NumPy, SciPy, matplotlib

* NumPy - multidimensional arrays and fundamental operations on them

* SciPy - Various math functionality (linear solvers, FFT, optimization, etc.)
  utilizing NumPy arrays

* matplotlib - plotting and data visualization

* None of these packages seek to clone MATLAB, if you want that try something
  like GNU Octave

### Python software stack

![fig](fig/python-stack.png)

## NumPy

NumPy provides a numeric array object:

In [1]:
import numpy as np
a = np.array([7, 42, -3])
print(a)

[ 7 42 -3]


In [2]:
a[1]

42

In [3]:
a[1] = 19
a

array([ 7, 19, -3])

### Arrays are not lists

In [4]:
a[0] = "hello"

ValueError: invalid literal for int() with base 10: 'hello'

In [5]:
a.append(8)

AttributeError: 'numpy.ndarray' object has no attribute 'append'

### NumPy arrays

* NumPy arrays contain **homogeneous** data (all elements must have same type)

* Size is fixed, i.e. you can't append or remove

### Data types

* Integers

  * 8, 16, 32, and 64 bit signed and unsigned (np.int8, np.uint8, etc.)

* Floating point

  * 32, 64, 128 bit (np.float32, np.float64, etc.)

* Complex, strings, and Python object references also supported

### Data type examples

In [6]:
a = np.array([ 7, 19, -3], dtype=np.float32)
a

array([  7.,  19.,  -3.], dtype=float32)

In [7]:
a[0] = a[0]/0.
a

/home/nwh/.local/lib/python3.5/site-packages/ipykernel/__main__.py:1: RuntimeWarning: divide by zero encountered in true_divide
  if __name__ == '__main__':


array([ inf,  19.,  -3.], dtype=float32)

In [8]:
b = np.array([4, 7, 19], dtype=np.int8)
b

array([ 4,  7, 19], dtype=int8)

In [9]:
b[0] = 437
b

array([-75,   7,  19], dtype=int8)

### Multidimensional arrays

* Arrays can have multiple dimensions called *axes*

* The number of *axes* is called the *rank*

* These terms come from the NumPy community and should not be confused with linear
  algebra terms for *rank*, etc.

### Multidimensional arrays

In [10]:
a = np.array([(7, 19, -3), (4, 8, 17)], dtype=np.float64)
a

array([[  7.,  19.,  -3.],
       [  4.,   8.,  17.]])

In [11]:
a.ndim

2

In [12]:
a.dtype

dtype('float64')

In [13]:
a.shape

(2, 3)

In [14]:
a.size

6

### Internal representation

![fig](fig/numpy-representation.png)

### Creating arrays

In [15]:
a = np.empty((3,3))
a

array([[  6.90680474e-310,   1.59679092e-316,   6.90679130e-310],
       [  6.90679130e-310,   6.90679131e-310,   6.90679130e-310],
       [  6.90680491e-310,   0.00000000e+000,   6.90680487e-310]])

In [16]:
a = np.zeros((3,3))
a

array([[ 0.,  0.,  0.],
       [ 0.,  0.,  0.],
       [ 0.,  0.,  0.]])

In [17]:
a = np.ones((3,3))
a

array([[ 1.,  1.,  1.],
       [ 1.,  1.,  1.],
       [ 1.,  1.,  1.]])

In [18]:
a = np.eye(3)
a

array([[ 1.,  0.,  0.],
       [ 0.,  1.,  0.],
       [ 0.,  0.,  1.]])

In [19]:
a = np.arange(9, dtype=np.float64)
a

array([ 0.,  1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.])

In [20]:
a = np.arange(9, dtype=np.float64).reshape(3,3)
a

array([[ 0.,  1.,  2.],
       [ 3.,  4.,  5.],
       [ 6.,  7.,  8.]])

### Reading data from a file

```sh
$ cat numbers.txt
7. 19. -3.
4. 8. 17.
```


In [21]:
a = np.loadtxt('numbers.txt', dtype=np.float64)
a

array([[  7.,  19.,  -3.],
       [  4.,   8.,  17.]])

In [22]:
a = a + 1
np.savetxt('numbers2.txt', a)

### Remove single dimension entry

In [23]:
a = np.arange(3)
a

array([0, 1, 2])

In [24]:
a.shape
b = np.arange(3).reshape(3,1)
print(b)
print(b.shape)
b = np.squeeze(b)
print(b)
print(b.shape)

[[0]
 [1]
 [2]]
(3, 1)
[0 1 2]
(3,)


### Array operations

In [25]:
a = np.arange(9, dtype=np.float64)
a

array([ 0.,  1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.])

In [26]:
# a slice
a[3:7]

array([ 3.,  4.,  5.,  6.])

In [27]:
# assign to a slice
a[3:7] = 0
a

array([ 0.,  1.,  2.,  0.,  0.,  0.,  0.,  7.,  8.])

In [28]:
2*a

array([  0.,   2.,   4.,   0.,   0.,   0.,   0.,  14.,  16.])

In [29]:
a*a

array([  0.,   1.,   4.,   0.,   0.,   0.,   0.,  49.,  64.])

In [30]:
sum(a)

18.0

In [31]:
min(a)

0.0

In [32]:
max(a)

8.0

### Array operations

In [33]:
a = np.arange(9, dtype=np.float64)
print(a)

# bad idea
total = 0.
for n in range(len(a)):
    total += a[n]*a[n]

math.sqrt(total)

[ 0.  1.  2.  3.  4.  5.  6.  7.  8.]


NameError: name 'math' is not defined

In [34]:
# better idea
import math
math.sqrt(np.dot(a,a))

14.2828568570857

In [35]:
# best idea
np.linalg.norm(a)

14.282856857085701

### Speed of array operations

In [36]:
%timeit total = sum(np.ones(1000000,dtype=np.int32))

10 loops, best of 3: 97.1 ms per loop


In [37]:
%timeit total = np.sum(np.ones(1000000,dtype=np.int32))

1000 loops, best of 3: 892 µs per loop


### Loops vs. array operations

* Loops you write in Python will be executed by the interpreter

* Some of the overloaded operators (e.g. `min`, `max`, `sum`, etc.) work albeit
  slowly

* Calling NumPy function or methods of the array object will invoke high
  performance implementations of these operations

### Matrix operations

In [38]:
a = np.arange(9, dtype=np.float64).reshape(3,3)
a

array([[ 0.,  1.,  2.],
       [ 3.,  4.,  5.],
       [ 6.,  7.,  8.]])

In [39]:
a.transpose()

array([[ 0.,  3.,  6.],
       [ 1.,  4.,  7.],
       [ 2.,  5.,  8.]])

In [40]:
np.trace(a)

12.0

In [41]:
a*a # element wise multiplication

array([[  0.,   1.,   4.],
       [  9.,  16.,  25.],
       [ 36.,  49.,  64.]])

In [42]:
np.dot(a,a) # matrix-matrix multiplication

array([[  15.,   18.,   21.],
       [  42.,   54.,   66.],
       [  69.,   90.,  111.]])

In [43]:
# new matrix multiply operator in Python 3.5
a @ a

array([[  15.,   18.,   21.],
       [  42.,   54.,   66.],
       [  69.,   90.,  111.]])

### array vs matrix

* NumPy has a dedicated matrix class

* However, the matrix class is not as widely used and there are subtle
  differences between a 2D array and a matrix

* It is highly recommended that you use 2D arrays for maximum compatibility with
  other NumPy functions, SciPy, matplotlib, etc.

* See here for more details:

<http://www.scipy.org/NumPy_for_Matlab_Users>

(`array' or `matrix'? Which should I use?)

### References to an array

In [44]:
a = np.arange(9, dtype=np.float64).reshape(3,3)
a

array([[ 0.,  1.,  2.],
       [ 3.,  4.,  5.],
       [ 6.,  7.,  8.]])

In [45]:
b = a
b[0,0] = 42
b

array([[ 42.,   1.,   2.],
       [  3.,   4.,   5.],
       [  6.,   7.,   8.]])

In [46]:
a

array([[ 42.,   1.,   2.],
       [  3.,   4.,   5.],
       [  6.,   7.,   8.]])

### Array slices and references

In [47]:
a = np.arange(9, dtype=np.float64)
a

array([ 0.,  1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.])

In [48]:
b = a[2:7]
b

array([ 2.,  3.,  4.,  5.,  6.])

In [49]:
b[2] = -1
b

array([ 2.,  3., -1.,  5.,  6.])

In [50]:
a

array([ 0.,  1.,  2.,  3., -1.,  5.,  6.,  7.,  8.])

### Array copies

In [51]:
a = np.arange(9, dtype=np.float64)
a

array([ 0.,  1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.])

In [52]:
b = a.copy()
b

array([ 0.,  1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.])

In [53]:
b[4] = -1
b

array([ 0.,  1.,  2.,  3., -1.,  5.,  6.,  7.,  8.])

In [54]:
a

array([ 0.,  1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.])

### Universal functions (ufuncs)

In [55]:
import numpy
a = np.arange(9, dtype=np.float64)
a

array([ 0.,  1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.])

In [56]:
import math
math.sqrt(a)

TypeError: only length-1 arrays can be converted to Python scalars

In [57]:
np.sqrt(a)

array([ 0.        ,  1.        ,  1.41421356,  1.73205081,  2.        ,
        2.23606798,  2.44948974,  2.64575131,  2.82842712])

### Beyond just arrays


* NumPy has some support for some useful operations beyond the usual vector and
  matrix operations:

  * Searching, sorting, and counting within arrays

  * FFT (Fast Fourier Transform)

  * Linear Algebra

  * Statistics

  * Polynomials

  * Random number generation

* SciPy has largely replaced much of this functionality,
  plus added much more

### Warning

* Once you start making use of extension modules such as NumPy, SciPy, etc. the
  chances of code "breaking" when you run it on different machines goes up
  significantly

* If you do some of your development on machines other than corn (which isn't
  the model we advise) you may run into issues

### Further Reading

* MATLAB users: <http://www.scipy.org/NumPy_for_Matlab_Users>
* NumPy tutorial at: <http://www.scipy.org/Tentative_NumPy_Tutorial>
* Official docs at: <http://docs.scipy.org/>